version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "banking-app"
stack_name = "banking-app"

[default.package.parameters]
resolve_s3 = true

[cognito]
[cognito.global]
[cognito.global.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
s3_prefix = "banking-app-cognito"
resolve_s3 = true
stack_name = "banking-app-cognito"
region = "eu-west-2"
parameter_overrides=[
    "Environment=cognito",
]