name: Lint and Format Check Code

on:
  pull_request:
  workflow_dispatch:

jobs:
  ruff-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          make init

      - name: Black Format Check
        run: make format-check

      - name: Ruff Check
        run: make lint
