name: Ruff Code

on:
  pull_request:
  workflow_dispatch:

jobs:
  ruff-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and setup python
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Ruff Format Check
        run: ruff format --check

      - name: Ruff Check
        run: ruff check