name: Test lambdas

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-lambdas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and setup python
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run tests
        run: pytest -vv
